name: Reuseable Workflow Caller

on:
  workflow_dispatch:

jobs:
  call-reuseable-workflow-path:
    name: Invoke reuseable workflow with relative path
    uses: ./.github/workflows/18-authoring-actions--02-reuseable-workflows-source.yaml
    with:
      foo: bar
      environment: staging
    secrets: inherit

  call-reuseable-workflow-sha:
    name: Invoke reuseable workflow with repo + commit hash
    uses: M-SARIBHANIF/Git-course-work/.github/workflows/18-authoring-actions--02-reuseable-workflows-source.yaml@master
    with:
      foo: bar
      environment: production
    secrets:
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}